services:
  - docker

before_install:
  - docker build -t skiffua/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skiffua/docker-react npm run test -- --coverage

deploy: {
  provider: "elasticbeanstalk",
  region: "us-east-1",
  app: "docker-react-test",
  env: "Dockerreacttest-env",
  bucket: "elasticbeanstalk-us-east-1-186018379257",
  bucket_path: "docker-react-test",
  on: {
    branch: [
     "master",
     ],
  },
  access_key_id: 
    secure: "$AWS_ACCESS_KEY",
  secret_access_key: 
    secure: "$AWS_SECRET_KEY",  
}  
