language: generic

services:
  - docker

deploy: {
  provider: "elasticbeanstalk",
  region: "eu-central-1",
  app: "docker-rc",
  env: "Dockerrc-env",
  bucket: "elasticbeanstalk-eu-central-1-186018379257",
  bucket_path: "docker-rc-test",
  on: {
    branch: [
     "master",
     ],
  },
  access_key_id: "$AWS_ACCESS_KEY",
  secret_access_key: "$AWS_SECRET_KEY",
}  
